<a href="https://colab.research.google.com/github/joshuareyesc/MetNumUN2023I/blob/main/Quiz1UNCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


This quiz was created originaly in:

- Python 3.6.9

- NumPy: 1.19.5

**Solution**

In [40]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
    if((x%3)==0):
      if((x%3==0)and(x%5==0)):
        answer="FizzBuzz!"
      else:
        answer="Fizz!"
    else:
      if((x%5)==0):
        if((x%5==0)and(x%3==0)):
          answer="FizzBuzz!"
        else:
          answer="Buzz!"
      else:
        answer="..."

      
    

   
    return answer


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


In [41]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


Expected output:
``` 
Fizz!
...
Buzz!
...
FizzBuzz!
```

**Solution**

In [13]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    num=[]
    ans = []
    if(n>0):
      for i in range(n):
        num.append(i+1)
      for j in range(len(num)):
        if((num[j]%3)==0):
          if(((num[j]%3)==0) and (num[j]%5)==0):
            ans.append("FizzBuzz!")
          else:
            ans.append("Fizz!") 
        else:
          if((num[j]%5)==0):
            if(((num[j]%3)==0) and ((num[j]%5)==0)):
              ans.append("FizzBuzz!")

            else:
              ans.append("Buzz!")
          else:
            ans.append("...")
      return ans 
    else:
      
     return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

In [16]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

In [17]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


**Solution**

In [38]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  
  X_standarized = ((X-X.mean())/X.std())


  return X_standarized

In [29]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))
print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
/*/////
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [34]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  
 

  np.diag(A)
  D =np.diag(np.diag(A))
  D.astype(float)

  return D.astype(float)