<a href="https://colab.research.google.com/github/joshuareyesc/MetNumUN2023I/blob/main/Quiz1_Python_NumPy_UNCode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


This quiz was created originaly in:

- Python 3.6.9

- NumPy: 1.19.5

## **1. *FizzBuzz*  - Python**

---

###**Problem Description**

**Task:** Given an integer $x$ return:
 

*   The string "**`Fizz!`**" if $x$ is divisible by $3$ and not  divisible by $5$.
*    The string "**`Buzz!`**" if $x$ is divisible by $5$ and not  divisible by $3$.
*    The string "**`FizzBuzz!`**" if $x$ is divisible by both $5$ and divisible by $3$.
*    The string "**`...`**" otherwise.

**Input Format:** The input consists of a single integer $x$. 

**Constraints:** $x$ is an integer

**Output Format:**  the output is a string.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

FizzBuzz(3)

#  --> Expected output: Fizz!

FizzBuzz(11)

#  --> Expected output: ...

FizzBuzz(5)
#  --> Expected output: Buzz!

FizzBuzz(7)
#  --> Expected output:...

FizzBuzz(15)
#  --> Expected output: FizzBuzz!
```

---

**Solution**

In [40]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
    if((x%3)==0):
      if((x%3==0)and(x%5==0)):
        answer="FizzBuzz!"
      else:
        answer="Fizz!"
    else:
      if((x%5)==0):
        if((x%5==0)and(x%3==0)):
          answer="FizzBuzz!"
        else:
          answer="Buzz!"
      else:
        answer="..."

      
    

   
    return answer


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


In [41]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


Expected output:
``` 
Fizz!
...
Buzz!
...
FizzBuzz!
```

---

###**Problem Description**

**Task:** Given an integer $n$ return the list with the *FizzBuzz* answers for the integer numbers $1$ to $n$ (including $n$).
  

**Input Format:** The input consists of a single integer $n$. 

**Constraints:** $n$ is an integer

**Output Format:**  list with the *FizzBuzz* answers, if the input is not positive return an empty list.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

FizzBuzzList(4)
#  --> Expected output: ['...', '...', 'Fizz!', '...']
 
FizzBuzzList(-1)
#  --> Expected output: []
```
---

**Solution**

In [13]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    num=[]
    ans = []
    if(n>0):
      for i in range(n):
        num.append(i+1)
      for j in range(len(num)):
        if((num[j]%3)==0):
          if(((num[j]%3)==0) and (num[j]%5)==0):
            ans.append("FizzBuzz!")
          else:
            ans.append("Fizz!") 
        else:
          if((num[j]%5)==0):
            if(((num[j]%3)==0) and ((num[j]%5)==0)):
              ans.append("FizzBuzz!")

            else:
              ans.append("Buzz!")
          else:
            ans.append("...")
      return ans 
    else:
      
     return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

In [16]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

## **3. *Standarize* - z scores - NumPy**

In [17]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


---

###**Problem Description**

**Task:** Given an numpy array $X$ return the corresponding standard scores.
  
**Input Format:** The input consists of a numpy array $X$. 

**Output Format:**  A numpy array with standard scores corresponding to $X$.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])
standarize(X0)

#  --> Expected output: array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

X1 = np.arange(5)
standarize(X1)

#  --> Expected output: array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

```
---

**Solution**

In [38]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  
  X_standarized = ((X-X.mean())/X.std())


  return X_standarized

## **4. *Main diagonal matrix*  - NumPy**

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** function ***`diag`***  and ***`astype`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [29]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))
print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
/*/////
[[1 0 0]
 [0 2 0]
 [0 0 3]]


---

###**Problem Description**

**Task:** Given a numpy matrix $A$ (2-D array) return the diagonal matrix with the elements of its main diagonal.
 

**Input Format:** The input consists of a numpy matrix $A$ (2-D array).

**Output Format:**  The diagonal matrix with the elemnts of its main diagonal.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

A = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])
```
---

In [34]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  
 

  np.diag(A)
  D =np.diag(np.diag(A))
  D.astype(float)

  return D.astype(float)

**¡Congratulations!** You have finished your first quiz.



## **Credits**
Created by 
  - German Hernandez
  - Oscar Fabian Sierra Daza
  
Modifying quizzes originaly created by
  - Felipe Restrepo Calle
  - Alberto Nicolai Romero Martínez
  - Miguel Angel Ortiz Marín
